In [8]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool
import matplotlib as plt
import matplotlib.pylab as plt
import seaborn as sns

In [ ]:

mysql = create_engine('mysql+pymysql://dev_emily_park:Emilypark123@service.cluster-cogfzn9i6pkm.ap-northeast-2.rds.amazonaws.com:4306/quicket?charset=utf8', encoding='utf-8')

db_uri = "postgresql+psycopg2://quicket:Wkdenfco666@172.31.254.37:5439/quicket"
old_dw = create_engine(db_uri, encoding='utf-8')

bun_dw = create_engine('postgresql+psycopg2://emily_park:Emilypark321#!@bun-dw.chlb9dm0sjmd.ap-northeast-2.redshift.amazonaws.com:5439/bunjang', encoding='utf-8')

In [46]:
from datetime import date, timedelta

start_date = date.today() - timedelta(days = 7)
end_date = date.today() - timedelta(days = 1)

print('get search history from', start_date, 'to', end_date)

get search history from 2020-08-06 to 2020-08-12

In [103]:
q_temp = f'''
SELECT s.page_id,
       s.ref_content,
       s.search_term,
       s.user_id
FROM bun_log_db.app_event_type_search s
JOIN
  (SELECT search_term
   FROM bun_log_db.app_event_type_search
   WHERE event_type = 'search'
     AND device_type IN ('a', 'i')
     AND YEAR||MONTH||DAY BETWEEN {start_date.strftime('%Y%m%d')} AND {end_date.strftime('%Y%m%d')}
   GROUP BY 1
   ORDER BY count(*) DESC
   LIMIT 1000) t ON s.search_term = t.search_term
WHERE s.event_type = 'search'
  AND s.device_type IN ('a', 'i')
  AND s.YEAR||s.MONTH||s.DAY BETWEEN {start_date.strftime('%Y%m%d')} AND {end_date.strftime('%Y%m%d')}
'''

q = '''
SELECT s.page_id,
       s.ref_content,
       s.search_term,
       s.user_id,
       CASE
           WHEN u.sex = 1 THEN 'female'
           WHEN u.sex = 2 THEN 'male'
           ELSE 'none'
       END AS sex,
       Coalesce(NULL, Ceil((Extract(DAY
                                    FROM Getdate() - u.birthdate :: timestamptz) / 365.25)), 0) AS age_detail,
       CASE
           WHEN age_detail < 20 THEN 10
           WHEN age_detail >= 20
                AND age_detail < 30 THEN 20
           WHEN age_detail >= 30
                AND age_detail < 40 THEN 30
           ELSE 40
       END AS age
FROM bun_log_db.app_event_type_search s
JOIN
  (SELECT search_term
   FROM bun_log_db.app_event_type_search
   WHERE event_type = 'search'
     AND device_type IN ('a',
                         'i')
     AND YEAR||MONTH||DAY BETWEEN {} AND {}
   GROUP BY 1
   ORDER BY count(*) DESC
   LIMIT 1000) t ON s.search_term = t.search_term
JOIN service1_quicket.user_extra_info u ON s.user_id = u.uid
WHERE s.event_type = 'search'
  AND s.device_type IN ('a',
                        'i')
  AND s.YEAR||s.MONTH||s.DAY BETWEEN {} AND {}
  AND u.is_identification = 1
  AND To_date(u.birthdate, 'YYYY-MM-DD') > '1900-01-01'
'''.format('\'' + start_date.strftime('%Y%m%d') + '\'', '\'' + end_date.strftime('%Y%m%d') + '\'', '\'' + start_date.strftime('%Y%m%d') + '\'', '\'' + end_date.strftime('%Y%m%d') + '\'')

print(q_temp)
# search = pd.read_sql(q, con=bun_dw)

SELECT s.page_id,
       s.ref_content,
       s.search_term,
       s.user_id
FROM bun_log_db.app_event_type_search s
JOIN
  (SELECT search_term
   FROM bun_log_db.app_event_type_search
   WHERE event_type = 'search'
     AND device_type IN ('a', 'i')
     AND YEAR||MONTH||DAY BETWEEN 20200806 AND 20200812
   GROUP BY 1
   ORDER BY count(*) DESC
   LIMIT 1000) t ON s.search_term = t.search_term
WHERE s.event_type = 'search'
  AND s.device_type IN ('a', 'i')
  AND s.YEAR||s.MONTH||s.DAY BETWEEN 20200806 AND 20200812

In [58]:
search['search_term'].nunique()

994

In [59]:
search['search_term'].unique()

array(['갤럭시탭s6', '조던1 스모크그레이', '아이폰', '노트북', '갤럭시노트10플러스', '키르시',
       '방탄소년단 ', '아이앱', '플레따', '갤럭시탭', '갤럭시노트9', '갤럭시노트10', '기프티콘', '세븐틴',
       '프라다가방', '크롬하츠', '보테가베네타', '아크메드라비 후드티', '나이키 반바지', '285', '금팔찌',
       '크로스백', '가디건', '아이폰xs', '슈콤마보니', '래쉬가드', '오리지널티켓', '프라이탁 블레어',
       '파타고니아', '구찌 스니커즈', '조거팬츠', 'bmw', '나이키', '볼링공', '실바니안', '책상',
       '몽블랑 카드지갑', '전자담배 기기', '컨버스', '아워레가시', '데이브레이크', '픽시', '로스트사가',
       '유앤진', '오도어', '닌텐도 3ds', '오프화이트 맨투맨', '발렌티노 스니커즈', '고야드 클러치',
       '슈프림', '아이앱 반팔', '캐릭캐릭체인지', '언노운', '아이폰xs 256', '문상', '숏패딩',
       '디스이즈네버댓', 'pcx', '노트10+', '필름카메라', '스톤아일랜드 맨투맨', '발렌시아가',
       '우포스 쪼리', '순금', '인소의 법칙', '나이키 바람막이', '바온', '구찌', '갤럭시s20', '일렉기타',
       '메트로시티', '광주', '크롭티', '키티', '베이비돌', '조던1', '브라', '골든티켓', '에어팟',
       '드바스크', '무료나눔', '보헤미안서울', '태블릿', '민물낚시대', '에어팟케이스', '갤럭시워치',
       '공기청정기', '루이비통 반지갑', '아이앱스튜디오 반팔', '입생로랑 카드지갑', '파우치', '아이폰7',
       '플스', '원피스', 'lmml', '노트10', 'cbr125', '롬앤', '마르지엘라', '버즈', '스위치',
       '런스타 하이크', '여자친구', '닌텐도', '맨투맨', '고야드 카드지갑', '스투시', '뱅드림 ', '인증번호',
       '갤럭시워치액티브2', '릭오웬스', '컨버스 런스타 하이크', '레고 ', '피파4', '280', 's8',
       '갤럭시버즈플러스', '여자아이들', '피파모바일', '알렉산더맥퀸', '인형', '꼼데가르송 반팔', '겐조',
       '삽니다', '에어팟 케이스', '키링', '나이키 윈드러너', '더보이즈', '스파이더', '아이폰8', '크록스',
       '마르지엘라 카드지갑', '샤넬 카드지갑', '아이폰se2', '에어팟2', '가면라이더', '위클리', '마이멜로디',
       '자라', '327', '270', '톰브라운 맨투맨', '디즈니', '건담', '아이즈원 ', '태그호이어',
       '아이패드 프로 3세대', '오마이걸', 'bmx', '투바투', '루이비통 카드지갑', '후드티', '아이폰6',
       '축구화', '볼링', '발렌시아가 트리플s', '리넨느', '갤럭시s10e', '세일러문 ', '까르띠에 팔찌',
       '메리다', '아이패드프로', '디아이콘', '14k반지', 'cgv', '버버리', '베이프 반팔', '롤 스킨',
       '소니엔젤', '스키니피그', '반지갑', '롤 rp', '아더에러', '발렌티노 클러치', '스와로브스키 목걸이',
       '여성골프웨어', '구찌 클러치', '언더아머', '크롬하츠 반지', '스톤아일랜드 바람막이', '피어오브갓',
       '구체관절인형', '코드유', '선글라스', '비비안웨스트우드', '은팔찌', '오나홀', '갤럭시 버즈 플러스',
       '아디다스', '폴더폰', '갤럭시 버즈 라이브', '속옷 ', '오드원아웃', '칼하트', '에어포스',
       '게이밍 노트북', '커피머신', '시티에이스', '엔진11 크릿디', '폼폼푸린', '팔찌', 'avp pro ',
       '톰브라운 가디건', '이지부스트350', '담전자배', '골프백', '버즈 라이브', '레니본', '구찌 지갑',
       '오프화이트', '바람막이', '튜닝카', '구찌 벨트', '대구', '미니백', '스톤아일랜드 ', '버즈라이브',
       '닌텐도스위치', '볼캡', '액티브2', '핸드폰', '아쿠비클럽', '아이유', '톰브라운 클러치', '모자',
       '목걸이', '아이폰 11', '엔지니어드가먼츠', '짱구', '아이패드 6세대', '유희왕', '스투시 반팔',
       '모배 ', '우영미', 'lvc', '르메르', '닌텐도 스위치 라이트', '벤리', '아이폰 se2', '남자시계',
       '육공다이어리', '에이블리', '디지몬', 'gs25', '배그 계정', '마스크', '오프화이트 반팔', '지갑',
       'iwc ', '언더커버', '뉴에라', '나눔', '발렌시아가 스피드러너', '크롬하츠 팔찌', '나이키 후드집업',
       '아이앱스튜디오 후드', '발렌티노 카드지갑', '꼼데가르송', '아이코스3듀오', '토니웩', '에쿠스',
       '컨버스 피어오브갓', '다이어트', '러브비트', '전자담배', '버즈플러스', '바이레도', '프레클',
       '갤럭시탭s6 라이트', '슈가슈가룬 ', '아벡데플뢰르', '아이앱스튜디오', '스피드러너',
       '스톤아일랜드 후드집업', '하이브리드 릴 2.0', '귀멸의 칼날', '나이키 모자', '컬쳐랜드', '아이들 ',
       '버킷햇', '에어팟1', '레인부츠', '금목걸이', '스타벅스 레디백', '메신저백', '아이코스', '쿠어',
       '프라다 카드지갑', 'nmax125', '쉬이즈큐트', '원피스 피규어', '지박소년 하나코군', 'v50',
       '폴라로이드 ', '꼼데가르송 보더티', '드림캐쳐', '에코백', '아이폰 se', 's10', 'v30',
       '쿠로미', '290', '애플워치5', '키티스트랩', '루이비통 클러치', '후드집업', '드래곤볼 ', '힙색',
       '갤럭시노트8', '드바스크 팔찌', 'rx580', '로드자전거', '메가박스', '롤', '젠틀몬스터', 'rrl',
       '아이스박스', '문화상품', '스컬프터', '우주소녀', '졸업사진', '축구공', '인스탁스', '까르띠에시계',
       '파라점퍼스 고비', '슈퍼커브', '메이윤', '아령', '미싱', '피스마이너스원', '아스트로 ', '슬링백',
       '미닛뮤트  ', '사카이', '에어팟프로', '갤럭시버즈라이브', '아이폰 x', '아이폰xr', '캠핑의자',
       '아크테릭스', '14k', '의자', '덤벨', '라코스테', '겐조 맨투맨', '아이즈원 폴라', '가방',
       '빵빵덕', '여성성인용품', '오프화이트 후드티', '코디스티커', '전기자전거 ', '신세계', '카브엠트',
       '구찌시계', '프로틴', '솔리드옴므 ', '갤럭시 폴드', '아이팟', '다마고치', '방탄 티머니', '청소기',
       '폴로 ', '뉴발란스 530', '하이큐', '쓰리타임즈', '마가린핑거스', '해피머니', '다꾸',
       '톰브라운 니트', '스니커즈', '몽클레어 반팔', '젝시믹스', '루이비통가방', '애플펜슬 1세대', '노트9',
       '플스4', '스푸닝', '아이앱 맨투맨', 'bt21', '다이어리', '나이키 신발', 'pcx125',
       '케이스티파이', '언더비', '뿌링클', '나이키 아노락', '갤럭시s9', '우산', '260', '앤더슨벨',
       '귀걸이', '메종마르지엘라', '캠핑카', '자이언트', '모노키니', '롱슬리브', '팬티', '미우미우 ',
       '노트5', '아이즈원 디아이콘', '구찌 반지갑', '교복', '스마트워치', '빔프로젝터', 'r3', '조이맥스',
       '오호라', 'mtb', '어리틀빗', '폴로셔츠', '갤럭시z플립 ', '베스파', 'z플립', '아이패드 미니5',
       '대전', '링피트', '쇼파', '엑소', '제이에스티나', '이달의소녀', '시어드', '향수', '드론',
       '에어컨', '에어팟 2', '딜도', '키보드', '안경', '구찌 반지', '정국', '14k팔찌', '싸인',
       '아이패드미니5', '스티커', '야마하 r3', 'lp', '프라이탁 ', '부산', '입생로랑', '구찌가방',
       '빅톤', '반스', '조던', 'gtx1060', '투썸', '루이비통 지갑', '아디다스 바람막이', 'iab',
       '이세이미야케', '세탁기', '디스크휠', '산리오', '맥케이지', '아이패드 프로 4세대', '마이프로틴',
       '톰브라운 카드지갑', 'cbr 125', '맥케이지 딕슨', '엔시티', '스톤', '아웃백', '메종키츠네 가디건',
       '투모로우바이투게더', '부산 오토바이', '아이패드 프로', '발로란트', '딥디크', '디올 카드지갑',
       '발렌티노 ', '타프', '액상', '코치', '냉장고', '아이폰11pro', '건조기', '케어베어',
       '고양이무료분양', '귀멸의칼날', '베지터블', '글러브', '에어팟 미개봉', '뉴발327', '휴대폰', '대차',
       '숄더백', '스케이트보드 ', '애플워치4', '몽블랑', '아미보', '롤렉스', '캠코더', '미스터트롯',
       '타미힐피거', '폴로 반팔', '셔츠', '럭키슈에뜨', '패딩', '포르자', '닥터마틴 ', '플랫베이스',
       '여자친구 포카', '전동스쿠터', '노트10플러스', '카니발', '아이즈원 응원봉', '피파 ', '생로랑',
       '무스너클 발리스틱 ', '전자레인지', '미스치프', '고야드', '로렉스 ', '게이밍의자', '유웰 칼리번',
       '미뉴에트', '방탄 ', '마마무 ', 'se2', '아이패드 ', '체리퀴리', '에어팟프로 미개봉',
       '발렌시아가 모자', '헬멧', '지브리', '나이키 스투시 아노락 ', '방탄포카 ', '티비', '디스퀘어드',
       '나이키에어맥스97', '프라다 호보백', '에이핑크', '릴', '무료분양', '비투비', '넘버나인 ',
       '로렉스시계', '폐호흡', '버버리 스니커즈', '아이폰11프로', '블랙핑크', '폴로 셔츠', '레플리카',
       '식탁', '아노락', '이마트', 'rx570', '레깅스', '방탄 앨범', '떡메', '스즈키 gsx-r125',
       '포르자300', '무스너클 ', '에어팟 2세대', '모닝', 'tv', '노트8', '침대', '오즈세컨',
       '구찌벨트', '마리마켓', '스파크', 'v40', '강아지', '캠핑용품', '핏플랍', '런닝머신', '고프로',
       '달빛천사', '백팩', '까르띠에', '가내스라', '영화', '트와이스', '브라운야드', 'msx125',
       '아이폰xs max', '샤넬가방', '펜디', '나이키 바지', '롱보드', '더블탭스', '모데스트무드',
       'xmax', '에어팟2 미개봉', 'nct', '컴퓨터본체', '투피스', 'a90', '모바일배그',
       '발렌시아가 반팔', '디올 ', '펑첸왕', '선풍기', '캠핑', 'avp', '갤럭시탭s5e', '프포',
       '나이키 베이퍼맥스', '18k팔찌', '14k목걸이', '랩핑지', '스타벅스 ', '아페쎄', '혼다cbr125',
       '컴퓨터 ', '미니냉장고', '낚시대', '텐트', '턴테이블', '마이크', '프라이탁 하와이파이브오', '펭수',
       '갤럭시워치3', '라벨르블랑', '프레드페리', '블루투스 이어폰', '롱원피스', '싸인볼', '강아지무료분양',
       '루이비통 팔찌', '리버풀', '고야드 반지갑', '본체', '이지부스트 ', '나이키 데이브레이크', '시엔느',
       '준지', '구찌 시계', '뉴발란스 ', '루이까또즈', '메이플스토리', '리멘트', '외장하드',
       '오메가 씨마스터', '치킨', '농구화', '무스너클 버니스웨터 ', '토리버치 ', '콘스탄틴 디스페랄',
       '프라다 ', '맨유', '톰브라운 ', '소니 wh-1000xm3', '무선청소기', '루이비통 ', '문화상품권',
       '네일팁', '위닉스 제습기', '스피커', '개인렌트', '성인용품', '쪼리', '알렉산더맥퀸 오버솔 ',
       '야구글러브', '안전화', '피아노', '디올 오블리크', '전담', '베이프 ', 'cos ', '디월트',
       '이디야', '토트넘', '입생로랑 클러치', '비타치', 'lg 벨벳', 'mtb자전거', '꼼데가르송 가디건 ',
       '이어폰', '클러치 ', '신박한정리', '캐피탈', '명품', '점프수트', '아이폰7플러스 ', '윤도영',
       's20 ', '코스', '뉴발란스327', '나이키 에어로로프트', '블랙박스', '러블리즈', '시눈 ',
       '빈티지 ', '치넬리 ', 'ps4 pro', '나이키 스투시 ', '골드바', '전자담배 액상', '오버워치 랭커',
       '오메가 ', '꿈빛파티시엘', '타이틀리스트', '베이퍼맥스', '지방시', '낚시', '나이키 오프화이트 ',
       '데스크탑', '벨트', 'k5', '갤럭시버즈 ', '라벨아카이브', '제습기 ', '비비탄', 'g7',
       '에어프라이어', 's9', '데이식스 ', '125cc ', '순금팔찌', '보이져300', '베스킨라빈스 ',
       '모동숲 ', '고양이 ', '탑스토니 ', '게이밍노트북 ', '애플펜슬 2세대', '콘스탄틴 ', '풋살화 ',
       '브라이틀링 ', '보테가베네타 클러치', '어항', '비앙키 ', '카드지갑 ', '동물의숲 ', '파리게이츠',
       '해밀턴', '킥보드', '에어팟 프로 미개봉', '방탄 랜박', '노스페이스 ', '샌디라이온 ', '라뇨 ',
       '더오픈프로덕트 ', '에어팟 프로 ', '발렌시아가 클러치', '아이패드에어3 ', '아이맥', '리본돌 ',
       '네일', '콘스탄틴 어베인 ', '폰테크', '카메라 ', '피파온라인4 ', '할리데이비슨', '핫토이 ',
       '헤드셋', '아이패드 미니', '갤럭시s20울트라 ', '갤럭시 버즈 ', '보드게임', '구관', '서든어택 ',
       '구찌 라이톤 ', '골프', '아이폰x ', '베르사체 ', '울산', '갤럭시s7', '청바지', '스타킹 ',
       '구찌모자', '몽클레어 ', '월광보합', '라코스테 원피스 ', '아이폰11 ', '유니폼 ', '파리바게트',
       '가민 ', '롯데시네마', '그래픽카드 ', '바비인형', '아이폰6s ', '이스트로그', '위너 ',
       '오토바이 ', '운동화', '아이폰 xs ', '자전거 ', '오버워치 ', '엔진11 ', '피치피치핏치 ',
       '가개통', '전동건 ', '김치냉장고', '파라점퍼스 ', '제5인격 ', '샤넬 ', '슈퍼주니어 ', '우포스 ',
       '닌텐도 스위치  ', '카트라이더 러쉬플러스 ', '골든구스 ', '하이틴 ', '아스날 ', '마르지엘라 독일군 ',
       '이누야샤 ', '아이폰 xr ', '씰스티커 ', '토이스토리 ', '98도씨 ', '로에베 ', '블라우스 ',
       '루프박스', '니들스 ', '레플 ', '낫띵리튼 ', '넷플릭스 ', '산드로 ', '메이플 ', '전담배 ',
       '뉴발란스 327 ', 'sf9 ', '비비안웨스트우드 목걸이 ', '갤럭시s10 ', '에고이스트 ', '널디 ',
       '팔라스 ', '전동킥보드 ', '포켓몬 ', '나이키 반팔 ', '닌텐도 스위치 동물의숲 에디션 ', '피마원 ',
       '로드 ', '벤츠 ', '18k ', '티쏘 ', '슬리퍼 ', '네이버후드 ', '홀복 ', 'ps4  ',
       '카트라이더 ', '샵마그넷 ', '도스노벤타 ', '반팔 ', '나이키 후드티 ', '포켓몬고 ', '세인트제임스 ',
       '아이폰8플러스 ', '셀린느 ', 'mngu ', '애플워치 ', '수영복 ', '버즈 플러스 ', '햄스터 ',
       '아더에러 메종키츠네 ', 'stu office ', '메종키츠네 ', 'iab studio ', '미스터트롯 서울 ',
       '해리포터 ', '가스건 ', '피규어 ', '애니인스 ', '휠셋 ', 'mcm  ', '트랜스포머 ', '세이코 ',
       '아크네 ', '티맥스 ', '지샥 ', '아이폰 8 ', '롤 계정 ', '보이져 ', '스파이더 반팔 ',
       '애플펜슬 ', '맥북 ', '입호흡 ', '비키니 ', '프라이탁 라씨 ', '네이더스 ', '아크메드라비 ',
       '방탄 포카 ', '나이키 테크팩 ', '루미녹스 ', '공기계 ', '젤네일 ', '쿠론 ', '모니터 ',
       '맥북프로 ', '아이패드 7세대 ', '엣라코 ', '데싱디바 ', '다이캐스트 ', '스페셜라이즈드 ', '풀샥 ',
       '마인크래프트 ', '나이키 사카이 ', '슬로우앤드 ', '베트멍 ', '금반지 ', '스쿠터 ',
       '나이키 더블스우시 ', '데상트 ', '아이패드 에어3 ', '애플워치3 ', '레진 ', 'cbr ',
       '위드아웃썸머 ', '전자렌지 ', 'cp컴퍼니 ', '런스타 ', '롤 아이디 ', '이달의 소녀 ', '슬라임 ',
       '블랙베리 ', '갤럭시폴드 ', '컨버스 척테일러 1970s ', '샌들 ', '제트플립 ', '보이져125 ',
       's10 5g ', '백예린 ', '에르메스 ', '갤럭시 워치 ', '노트20 ', '인스 ', '판도라 ',
       '게임보이 ', '밀크코코아 ', '원피스 레진 ', '중고폰 ', '로지텍 ', 's10e ', '자라 원피스 ',
       '헌터 레인부츠 ', '오라리 ', '오버워치 계정 ', '나이키스투시 ', '반바지 ', '메이비베이비 ',
       '맥퀸 ', '마뗑킴 ', '파워레인저 ', '코스프레 ', '톰브라운 셔츠 ', '추천인 ', '헤리티지플로스 ',
       '보이즈베어 ', '담배 ', '나이키 맨투맨 ', '아이폰8+ ', '아이폰 7 ', '빈티지 원피스 ', '교신 ',
       '조말론 ', 'acg ', '부산 보이져 ', '골프채 ', '뉴발란스 992 ', 'ssd ', '갤럭시s8 ',
       '스팀배그 ', '꼼데가르송 컨버스 ', 'nmax ', '신발 ', '클러치백 ', '꼼데 ', '다이슨 ',
       'v50s ', '메종키츠네 반팔 ', 'lmc ', 'xmax300  ', '몽클레어 패딩 ', '중고차 ',
       '뉴발란스 993 ', '반지 ', '스타벅스 텀블러 ', '솔로이스트 ', '시계 ', '제네시스쿠페 ', '마샬 ',
       '윤은혜 ', '키드밀리 ', '라프시몬스  ', '블루투스 스피커 ', 'bts ', '아이폰se  ',
       '소우소우 ', '장지갑 ', '레오폴드 ', '맥북에어 ', '유스랩 ', '게이밍컴퓨터 ', '자동차 ',
       '기타 ', '롤계정 ', '구찌 카드지갑 ', '반팔티 ', '롤 다이아 ', '구찌지갑 ', '레드벨벳  ',
       '메이플 계정 '], dtype=object)

In [118]:
start_date = date.today() - timedelta(days = 180)

q_temp = '''
SELECT i.viewer_uid,
       i.target_id,
       i.ref_page,
       i.keyword,
       i.seller_uid,
       split_part(i.ad_ref, '_', 4) AS pu_id,
       split_part(i.ad_ref, '_', 5) AS bid,
       p.price,
       p.category_id
FROM item_click_log6 i
JOIN product_info_for_stats p ON i.target_id = p.pid
WHERE i.updated BETWEEN {} AND {}
  AND i.ad_ref LIKE '%power_up%'
'''.format('\'' + str(start_date) + '\'', '\'' + str(end_date) + '\'')

q = '''
SELECT i.keyword,
       split_part(i.ad_ref, '_', 5) AS bid
FROM item_click_log6 i
WHERE i.updated BETWEEN {} AND {}
  AND i.ad_ref LIKE '%power_up%'
GROUP BY 1,
         2
'''.format('\'' + str(start_date) + '\'', '\'' + str(end_date) + '\'')
print(q)
# power_up_bid = pd.read_sql(q, con=old_dw)

SELECT i.keyword,
       split_part(i.ad_ref, '_', 5) AS bid
FROM item_click_log6 i
WHERE i.updated BETWEEN '2020-02-15' AND '2020-08-12'
  AND i.ad_ref LIKE '%power_up%'
GROUP BY 1,
         2

In [119]:
power_up_bid = pd.read_csv('power_up_bid.csv')
power_up_bid.head()

  keyword  bid
0    발렌티노  150
1     NaN   91
2   컴퓨터본체   83
3    rp충전  140
4     컴퓨터   87

In [60]:
search.head()

  page_id ref_content search_term  user_id   sex  age_detail  age
0      검색        None      갤럭시탭s6  1486131  male        25.0   20
1      검색       최근검색어  조던1 스모크그레이  9531584  male        24.0   20
2      검색       최근검색어         아이폰  6149319  male        27.0   20
3      검색        None         노트북  5624058  male        32.0   30
4      검색        None  갤럭시노트10플러스   396581  male        27.0   20

In [120]:
search.columns = ['page_id', 'ref_content', 'keyword', 'user_id', 'sex', 'age_detail', 'age']
df = pd.merge(power_up_bid, search, on = 'keyword', how = 'right')

In [123]:
df['bid'] = df['bid'].fillna(0)

In [91]:
# search['keyword'] = search['keyword'].fillna('')
# search['uid'] = search['uid'].astype(str)
# power_up_bid['keyword'] = power_up_bid['keyword'].fillna('')
# power_up_bid['uid'] = power_up_bid['uid'].astype(str)


# df = pd.merge(power_up_bid, search, on = ['keyword', 'uid'])

In [97]:
df['keyword'].nunique()

994

In [121]:
df[~df['bid'].isna()]['keyword'].nunique()

500

In [99]:
data = df.dropna()

In [101]:
data['keyword'].nunique()

241

In [124]:
df.groupby('keyword').agg({'bid':lambda x: list(set(x))})

                                                           bid
keyword
125cc                                                    [0.0]
14k          [130.0, 132.0, 134.0, 145.0, 150.0, 152.0, 50....
14k목걸이       [100.0, 122.0, 134.0, 105.0, 110.0, 80.0, 81.0...
14k반지        [130.0, 100.0, 134.0, 105.0, 80.0, 81.0, 50.0,...
14k팔찌        [98.0, 105.0, 80.0, 81.0, 50.0, 83.0, 93.0, 82...
18k                                                      [0.0]
18k팔찌        [100.0, 135.0, 105.0, 110.0, 80.0, 112.0, 81.0...
260                                [120.0, 290.0, 80.0, 150.0]
270                                       [80.0, 140.0, 260.0]
280                                        [80.0, 98.0, 230.0]
285                                                     [80.0]
290                                                     [80.0]
327          [130.0, 260.0, 390.0, 140.0, 150.0, 280.0, 160...
98도씨                                                     [0.0]
a90                                               [80.0, 50.0]
acg                                                      [0.0]
avp                                                      [0.0]
avp pro                                                  [0.0]
bmw                                                     [80.0]
bmx                                                      [0.0]
bt21                                                     [0.0]
bts                                                      [0.0]
cbr                                                      [0.0]
cbr 125                                                  [0.0]
cbr125                                                   [0.0]
cgv                                                     [80.0]
cos                                                      [0.0]
cp컴퍼니                                                    [0.0]
g7                                                      [80.0]
gs25                                                     [0.0]
...                                                        ...
피치피치핏치                                                   [0.0]
피파                                                       [0.0]
피파4          [131.0, 132.0, 135.0, 140.0, 142.0, 150.0, 280...
피파모바일                                                    [0.0]
피파온라인4                                                   [0.0]
픽시                                                [50.0, 85.0]
필름카메라                                             [80.0, 90.0]
핏플랍                                                      [0.0]
하이브리드 릴 2.0                                              [0.0]
하이큐                                                     [50.0]
하이틴                                                      [0.0]
할리데이비슨                                                   [0.0]
핫토이                                                      [0.0]
해리포터                                                     [0.0]
해밀턴                                               [80.0, 50.0]
해피머니         [50.0, 80.0, 81.0, 82.0, 83.0, 86.0, 88.0, 90....
핸드폰          [260.0, 390.0, 520.0, 140.0, 270.0, 400.0, 146...
햄스터                                                      [0.0]
향수           [130.0, 260.0, 261.0, 265.0, 140.0, 270.0, 271...
헌터 레인부츠                                                  [0.0]
헤드셋                                                     [80.0]
헤리티지플로스                                                  [0.0]
헬멧                                                      [80.0]
혼다cbr125                                                 [0.0]
홀복                                                       [0.0]
후드집업                                                    [80.0]
후드티                                 [80.0, 170.0, 90.0, 110.0]
휠셋                                                       [0.0]
휴대폰          [530.0, 540.0, 560.0, 50.0, 590.0, 80.0, 81.0,...
힙색                          [160.0, 80.0, 183.0, 120.0, 220.0]

[994 rows x 1 columns]